### ISSUE TITLE
This works with React-Native?

### ISSUE THREAD

**Issue by ArmandoAssuncao** [truffls/storybook-addon-intl#13]
Hi, i'm trying use this addon, but it cause this error:

<img src="https://user-images.githubusercontent.com/12402128/31946368-652f2bde-b8b0-11e7-9390-3856f547eee6.png" width="300" height="500">

I'm using the code example of the README. The error occurs when the `setIntlConfig` function is executed.
```
setIntlConfig({
    locales: ['en', 'de'],
    defaultLocale: 'en',
    getMessages
})
```

So, this is a bug or this addon not support RN? thanks

RN: 0.48.4
addon-intl: 2.1.2

**Comment by floriangosse** [comment]
I don't use React-Native and have no setup to test it. I seems to be a bug.

If you have time to check what is wrong and provide a PR this would be really nice. :)

**Comment by matteocng** [comment]
@ArmandoAssuncao I solved this issue (with React, not Native, so it may not work for you, as written in the [storybook docs](https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel)) by installing `@storybook/addon-actions` in the `devDependencies`, otherwise the various addons may require different versions of it. Working `package.json`:

```
  "devDependencies": {
    ...,
    "@storybook/addon-actions": "^3.2.14",
    "@storybook/addon-centered": "^3.2.14",
    "@storybook/addon-links": "^3.2.14",
    "@storybook/addons": "^3.2.14",
    "@storybook/react": "^3.2.14",
    ...
  }
```

**Comment by floriangosse** [comment]
@matteocng do you have time to provide a PR? :)
