### ISSUE TITLE
Add RTL / LTR Toggle

### ISSUE THREAD

**Issue by soundyogi** [truffls/storybook-addon-intl#21]
This project does not work anymore:
https://github.com/joscha/storybook-addon-i18n-tools

Since a rtl/ltr toggle would make sense for some languages.

Can we include one? :)

**Comment by floriangosse** [comment]
Thanks for your feedback. 😃  I think it's to much to handle the text direction in the addon. It only provides the possibility to switch it between the locale.

If you want to support rtl/ltr you should think about a solution which handles it based on the locale. `react-intl` currently doesn't provide the direction for texts. But you could make use of [`rtl-detect`](https://www.npmjs.com/package/rtl-detect) and create a small decorator for storybook which sets the direction automatically based on the language.

Here a small example:
```js
import * as React from 'react';
import { injectIntl } from 'react-intl';
import rtlDetect from 'rtl-detect';

class TextDirectionSetter extends React.Component {
    componentDidMount () {
        document.body.dir = rtlDetect.getLangDir(this.props.intl.locale);
    }

    componentDidUpdate () {
		document.body.dir = rtlDetect.getLangDir(this.props.intl.locale);
    }

	render () {
        return this.props.children || null;
    }
}

const TextDirectionSetterWithIntl = injectIntl(TextDirectionSetter);

export default (story) => {
	return (
		<TextDirectionSetterWithIntl>
			{story()}
		<TextDirectionSetterWithIntl>
    );
};
```

This decorator have to be added after `storybook-addon-intl` was register because it needs the `intl` context.

I have to say that I didn't test the code and just wrote it down based on what I think how it could work. 😄 If you have further questions I'm will try to help.

**Comment by soundyogi** [comment]
Thanks you so much for considering and the awesome answer!

<3 <3 <3
